services:

  jtr-development:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    container_name: jtr
    entrypoint: [ "/opt/scripts/provisioning/provision.sh" ]
    environment:
      FLASK_ENV: 'development'
      CACHE_REDIS_HOST: '0.0.0.0'
      CACHE_REDIS_PORT: '6379'
      CELERY_APP_NAME: 'tasks'
      CELERY_BROKER_NAME: 'worker'
      CELERY_BACKEND_URL: 'amqp://backend:mypass@localhost:5672'
      CELERY_WORKER_URL: 'amqp://worker:mypass@localhost:5672'
      CELERY_RESULT_BACKEND: 'rpc://'
      DATABASE_URL: 'mysql+pymysql://user:password@localhost:3306/jtr'
      MAIL_SERVER: '0.0.0.0'
      MAIL_PORT: '25'
      MAIL_USE_TLS: 'False'
      MAIL_USERNAME: None
      MAIL_PASSWORD: None
      MAIL_DEFAULT_SENDER: 'jtr@localhost'
      MYSQL_DATABASE: 'jtr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      GENERATE_TEST_DATA: True
      RABBITMQ_WORKER_PASS: 'mypass'
      RABBITMQ_WORKER_USER: 'worker'
      RABBITMQ_BE_PASS: 'mypass'
      RABBITMQ_BE_USER: 'backend'
      SECRET_KEY: 'secret'
    ports:
      - "127.0.0.1:80:80/tcp"
      - "127.0.0.1:443:443/tcp"
      - "127.0.0.1:3306:3306/tcp"
      - "127.0.0.1:8080:8080/tcp"
      - "127.0.0.1:15672:15672/tcp"
    extra_hosts:
      - "jugger-tourna.local:127.0.0.1"
      - "m.jugger-tourna.local:127.0.0.1"
      - "cdn.jugger-tourna.local:127.0.0.1"
    volumes:
      - .:/home:delegated
      - mysql_db_data:/var/lib/mysql
      - ./frontend/dist/apps:/usr/share/nginx/html:delegated
      - ./docker/development/assets:/home/backend/DataDomain/assets
      - ./docker/development/assets:/usr/share/nginx/html/assets

volumes:
  mysql_db_data: {}
