services:

  jtr-development:
    image: ghcr.io/leandercs/jtr:latest-arm64
    container_name: jtr
    entrypoint: [ "/opt/scripts/provisioning/entrypoint.sh" ]
    environment:
      FLASK_ENV: 'development'
      CACHE_REDIS_HOST: 'localhost'
      CACHE_REDIS_PORT: '6379'
      CELERY_APP_NAME: 'tasks'
      CELERY_BROKER_NAME: 'worker'
      CELERY_BROKER_URL: 'amqp://admin:mypass@localhost:5672'
      CELERY_RESULT_BACKEND: 'rpc://'
      DATABASE_URL: 'mysql+pymysql://user:password@localhost:3307/jtr'
      MYSQL_DATABASE: 'jtr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'mypass'
      RABBITMQ_DEFAULT_USER: 'admin'
    ports:
      - "3307:3307"
      - "5001:5001"
      - "5672:5672"
      - "6379:6379"
      - "15672:15672"
    volumes:
      - .:/home:delegated
      - mysql_db_data:/var/lib/mysql

volumes:
  mysql_db_data: {}
