openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/team-frontend/accept-team-invitation:
    post:
      summary: Accept team invitation
      operationId: acceptTeamInvitation
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '403':
          description: Forbidden

        '500':
          description: Internal Server Error
