openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/team-frontend/get-team-details/{escapedName}:
    get:
      summary: Get team details
      operationId: getTeamDetails
      parameters:
        - name: escapedName
          in: path
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK
