openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/create-team:
    post:
      summary: Create team
      operationId: createTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTeamRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    CreateTeamRequestBody:
      type: object
      properties:
        name:
          type: string
        city:
          type: string
        isMixTeam:
          type: boolean
        trainingTime:
          type: string
        aboutUs:
          type: string
        contacts:
          type: array
          items:
            type: string
