openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/create-participation:
    post:
      summary: Create participation of team
      operationId: createParticipation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateParticipationRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '500':
          description: Internal Server Error

components:
  schemas:
    CreateParticipationRequestBody:
      type: object
      properties:
        teamId:
          type: number
        tournamentId:
          type: number
