openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/create-fake-tournament:
    post:
      summary: Create fake
      operationId: createFake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournamentId:
                  type: integer

      responses:
        '200':
          description: OK

  /api/customer-frontend/create-fake-teams:
    post:
      summary: Create fake
      operationId: createFake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournamentId:
                  type: integer

      responses:
        '200':
          description: OK

  /api/customer-frontend/create-fake-users:
    post:
      summary: Create fake
      operationId: createFake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournamentId:
                  type: integer

      responses:
        '200':
          description: OK

  /api/customer-frontend/create-fake-is-part-of:
    post:
      summary: Create fake
      operationId: createFake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournamentId:
                  type: integer

      responses:
        '200':
          description: OK

  /api/customer-frontend/create-fake-participates_in:
    post:
      summary: Create fake
      operationId: createFake
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tournamentId:
                  type: integer

      responses:
        '200':
          description: OK
