openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/delete-participation:
    delete:
      summary: Delete participation
      operationId: deleteParticipation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteParticipationRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '403':
          description: Forbidden

        '500':
          description: Internal Server Error

components:
  schemas:
    DeleteParticipationRequestBody:
      type: object
      required:
        - teamId
        - tournamentId
      properties:
        teamId:
          type: number
        tournamentId:
          type: number
