openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/get-tournament-details/{tournamentId}:
    get:
      summary: Get tournament details
      operationId: getTournamentDetails
      parameters:
        - name: tournamentId
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: OK
