openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/get-team-overview:
    get:
      summary: Get team overview
      description: Returns a list of teams.
      responses:
        '200':
          description: A list of teams

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
