openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/get-tournament-overview:
    get:
      summary: Get tournament overview
      description: Returns a list of the upcoming tournaments.
      responses:
        '200':
          description: A list of tournaments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    tournament_id:
                      type: integer
                      description: The unique ID of the tournament
                      example: 123
                    logo:
                      type: string
                      description: The logo of the tournament's organizer team
                      example: "https://example.com/logo.png"
                    start_date:
                      type: string
                      format: date-time
                      description: The start date of the tournament
                      example: "2024-10-20T12:00:00"
                    total_teams:
                      type: integer
                      description: The total number of teams participating in the tournament
                      example: 10
                    registered_teams:
                      type: integer
                      description: The number of teams that are officially registered (not on the waiting list)
                      example: 8
                    tournament_name:
                      type: string
                      description: The name of the tournament
                      example: "Summer Cup"

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
