openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/get-tournament-overview:
    get:
      summary: Get tournament overview
      description: Returns a list of the upcoming tournaments.
      responses:
        '200':
          description: A list of tournaments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: The unique ID of the tournament
                      example: 123
                    location:
                      type: string
                      description: The location of the tournament
                      example: "New York"
                    name:
                      type: string
                      description: The name of the tournament
                      example: "Summer Cup"
                    organizerLogo:
                      type: string
                      description: The logo of the tournament's organizer team
                      example: "https://example.com/logo.png"
                    registeredTeams:
                      type: number
                      description: The number of teams that have registered for the tournament
                      example: 5
                    startDate:
                      type: string
                      format: date-time
                      description: The start date of the tournament
                      example: "2024-10-20T12:00:00"
                    totalTeams:
                      type: number
                      description: The total number of teams participating in the tournament
                      example: 10

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
