openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/customer-frontend/update-team:
    put:
      summary: Update team
      operationId: updateTeam
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTeamRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad Request

        '401':
          description: Unauthorized

        '404':
          description: Team not Found

        '500':
          description: Internal Server Error

components:
  schemas:
    UpdateTeamRequestBody:
      type: object
      required:
        - teamId
      properties:
        teamId:
          type: number
        name:
          type: string
        logo:
          type: string
          format: binary
        founded:
          type: string
          format: date
        city:
          type: string
        isMixTeam:
          type: boolean
        trainingTime:
          type: string
        aboutUs:
          type: string
        contacts:
          type: array
          items:
            type: string
