openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/create-password-reset:
    post:
      summary: Creates a passwort reset request
      operationId: createPasswordReset
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePasswordResetRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad request

        '500':
          description: Internal server error

components:
  schemas:
    CreatePasswordResetRequestBody:
      type: object
      required:
        - email
      properties:
        email:
          type: string
