openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/create-new-password:
    put:
      summary: Creates a new passwort from a reset request
      operationId: createNewPassword
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNewPasswordRequestBody'

      responses:
        '200':
          description: OK

        '400':
          description: Bad request

        '500':
          description: Internal server error

components:
  schemas:
    CreateNewPasswordRequestBody:
      type: object
      required:
        - hash
        - password
      properties:
        hash:
          type: string
        password:
          type: string
