openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/get-user-details/{escapedUsername?}:
    get:
      summary: Get user details
      operationId: getUserDetails
      parameters:
        - name: escapedUsername
          in: path
          required: false
          schema:
            type: string

      responses:
        '200':
          description: OK
