openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/get-user-picture:
    get:
      summary: Get user picture
      operationId: getUserPicture

      responses:
        '200':
          description: OK
          content:
            image/jpeg|image/png:
              schema:
                type: string
                format: binary
