openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/is-admin-of-organizer/{tournamentId}:
    get:
      summary: Is user an admin of the organizing team?
      operationId: isAdminOfOrganizer
      parameters:
        - name: tournamentId
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsAdminOfOrganizerResponseBody'

        '404':
          description: Not Found

        '500':
          description: Internal server error

components:
  schemas:
    IsAdminOfOrganizerResponseBody:
      type: number
