openapi: 3.0.0
info:
  title: Customer Frontend API
  version: 1.0.0
paths:
  /api/user-frontend/is-member-of-team/{escapedName}:
    get:
      summary: Is user an member of the team?
      operationId: isMemberOfTeam
      parameters:
        - name: escapedName
          in: path
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsMemberOfTeamResponseBody'

        '404':
          description: Not Found

        '500':
          description: Internal server error

components:
  schemas:
    IsMemberOfTeamResponseBody:
      type: number
