name: frontend

on: [push]

permissions:
  actions: read
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-frontend-${{ hashFiles('frontend/Dockerfile.test', 'frontend/**') }}
          restore-keys: |
            ${{ runner.os }}-docker-frontend-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.test
          tags: frontend-test:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull frontend-test image
        run: docker pull frontend-test:latest || echo "No cache found, running build instead"

      - name: Run tests
        run: docker run frontend-test nx run-many --target=test --all

  code-style:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull frontend-test image
        run: docker pull frontend-test:latest || echo "No cache found, running build instead"

      - name: Run code style checks
        run: docker run frontend-test nx run-many --target=lint --all
