name: Test Coverage Comment

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-backend
          key: ${{ runner.os }}-docker-backend-${{ hashFiles('backend/Dockerfile', 'backend/**') }}
          restore-keys: |
            ${{ runner.os }}-docker-backend-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          tags: backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache-backend
          cache-to: type=local,dest=/tmp/.buildx-cache-backend,mode=max

  backend-coverage:
    needs: backend-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull backend image
        run: docker pull backend:latest || echo "No cache found, running build instead"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Build coverage files
        run: docker run -v /tmp:/tmp backend python3 -m pytest --junitxml=/tmp/pytest.xml --cov=/app | tee /tmp/pytest-coverage.txt

      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            /tmp/pytest.xml
            /tmp/pytest-coverage.txt

  backend-coverage-comment:
    needs: backend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download backend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          report-only-changed-files: true
          remove-link-from-badge: true
          badge-title: Coverage
          junitxml-title: Backend coverage

  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-frontend
          key: ${{ runner.os }}-docker-frontend-${{ hashFiles('frontend/Dockerfile.test', 'frontend/**') }}
          restore-keys: |
            ${{ runner.os }}-docker-frontend-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.test
          tags: frontend-test:latest
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend,mode=max

  frontend-coverage:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull frontend image
        run: docker pull frontend-test:latest || echo "No cache found, running build instead"

      - name: Build coverage files
        run: docker run -v /tmp:/tmp frontend-test npx jest --reporters=default --reporters=jest-junit --coverage --no-cache | tee /tmp/jest-coverage.txt

      #- name: Build summary files
      #  run: docker run -v /tmp:/app/coverage frontend-test npx jest --coverage --coverageReporters json-summary --no-cache --verbose

      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            /tmp/jest-coverage.txt
            /tmp/junit.xml
            #/tmp/coverage-summary.json

  frontend-coverage-comment:
    needs: frontend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download frontend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          #coverage-summary-path: coverage-summary.json
          coverage-path: jest-coverage.txt
          junitxml-path: junit.xml
          report-only-changed-files: true
          badge-title: Coverage
          title: Frontend coverage
