name: Test Coverage Comment

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  backend-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Build coverage files
        run: |
          PYTHONPATH=backend pytest --junitxml=/tmp/pytest.xml --cov=backend --cov-config=backend/.coveragerc  | tee /tmp/pytest-coverage.txt

      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            /tmp/pytest.xml
            /tmp/pytest-coverage.txt

  backend-coverage-comment:
    needs: backend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download backend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          report-only-changed-files: true
          remove-link-from-badge: true
          badge-title: Coverage
          junitxml-title: Backend coverage

  frontend-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --prefix frontend

      - name: Build coverage files
        run: |
          cd frontend
          npx jest --reporters=default --reporters=jest-junit --coverage --no-cache | tee /tmp/jest-coverage.txt
    #- name: Build summary files
    #  run: docker run -v /tmp:/app/coverage frontend-test npx jest --coverage --coverageReporters json-summary --no-cache --verbose

      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            /tmp/jest-coverage.txt
            /tmp/junit.xml
            #/tmp/coverage-summary.json

  frontend-coverage-comment:
    needs: frontend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download frontend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          #coverage-summary-path: coverage-summary.json
          coverage-path: jest-coverage.txt
          junitxml-path: junit.xml
          report-only-changed-files: true
          badge-title: Coverage
          title: Frontend coverage
