name: Test Coverage Comment

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  backend-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull backend image from GHCR
        run: docker pull ghcr.io/leandercs/jtr-backend:latest-amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Build coverage files
        run: docker run --rm \
          -v $(pwd)/backend:/app \
          -v /tmp:/tmp \
          ghcr.io/leandercs/jtr-backend:latest-amd64 \
          python3 -m pytest --junitxml=/tmp/pytest.xml --cov=/app | tee /tmp/pytest-coverage.txt

      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: |
            /tmp/pytest.xml
            /tmp/pytest-coverage.txt

  backend-coverage-comment:
    needs: backend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download backend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          report-only-changed-files: true
          remove-link-from-badge: true
          badge-title: Coverage
          junitxml-title: Backend coverage

  frontend-coverage:
    needs: frontend-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull frontend-test image from GHCR
        run: docker pull ghcr.io/leandercs/jtr-frontend-test:latest-amd64

      - name: Build coverage files
        run: docker run --rm  \
          -v $(pwd)/frontend:/app \
          -v /tmp:/tmp  \
          ghcr.io/leandercs/jtr-frontend-test:latest-amd64 \
          /bin/bash -c "npm install && npx jest --reporters=default --reporters=jest-junit --coverage --no-cache | tee /tmp/jest-coverage.txt"

      #- name: Build summary files
      #  run: docker run -v /tmp:/app/coverage frontend-test npx jest --coverage --coverageReporters json-summary --no-cache --verbose

      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: |
            /tmp/jest-coverage.txt
            /tmp/junit.xml
            #/tmp/coverage-summary.json

  frontend-coverage-comment:
    needs: frontend-coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download frontend coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          #coverage-summary-path: coverage-summary.json
          coverage-path: jest-coverage.txt
          junitxml-path: junit.xml
          report-only-changed-files: true
          badge-title: Coverage
          title: Frontend coverage
